version: '3.7'

services:
  app:
    container_name: django_app
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn --reload backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../src/:/WWW/
    expose:
      - 8000
      - 2222:22
    env_file: .env
    depends_on:
      - db
    stdin_open: true
    tty: true

  nginx:
    image: nginx:alpine
    container_name: django_nginx
    restart: always
    volumes:
      - ../src/:/WWW/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
      - ./logs:/var/log/nginx
    ports:
      - 8080:80
      - 443:443
    depends_on:
      - app

  db:
    container_name: db_postgres
    image: postgres:alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.db

volumes:
  postgres_data:
  static_volume:
  media_volume:
