# Generated by Django 3.0 on 2019-12-29 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='currency',
            new_name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('MW', 'Man and Woman')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='promo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='brandID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Brand'),
            preserve_default=False,
        ),
    ]
